#!/bin/bash
set -ex

BUILD_ARCH=$(echo "$DOCKER_TAG" | cut -d '-' -f 1)
CERTBOT_VERSION=$(echo "$DOCKER_TAG" | cut -d '-' -f 2 | sed "s/v//")

docker build --build-arg CERTBOT_VERSION="${CERTBOT_VERSION}" -f "${DOCKERFILE_PATH}" -t "${DOCKER_REPO}:${BUILD_ARCH}-v${CERTBOT_VERSION}" .
