#!/bin/bash
set -ex

WORK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source "$WORK_DIR/../../lib/common"

TARGET_ARCH=$(GetTargetArchFromTag "$DOCKER_TAG")
QEMU_ARCH=$(GetQemuArchFromTag "$DOCKER_TAG")
CERTBOT_VERSION=$(GetCerbotVersionFromTag "$DOCKER_TAG")

docker build \
    --build-arg CERTBOT_VERSION="${CERTBOT_VERSION}" \
    --build-arg TARGET_ARCH="${TARGET_ARCH}" \
    --build-arg QEMU_ARCH="${QEMU_ARCH}" \
    -f "${DOCKERFILE_PATH}" \
    -t "${DOCKER_REPO}:${TARGET_ARCH}-v${CERTBOT_VERSION}" \
    .
