#!/bin/bash
set -ex

WORK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source "$WORK_DIR/../../lib/common"

DEFAULT_ARCH="amd64"
CERTBOT_VERSION=$(GetCerbotVersionFromTag "$DOCKER_TAG")

TagImage() {
    docker tag "${DOCKER_REPO}:$1" "${DOCKER_REPO}:$2"
    docker push "${DOCKER_REPO}:$2"
}

for TARGET_ARCH in "${ALL_TARGET_ARCH[@]}"; do
    TagImage "${TARGET_ARCH}-v${CERTBOT_VERSION}" "${TARGET_ARCH}-latest"
    if [ "${TARGET_ARCH}" == "${DEFAULT_ARCH}" ]; then
        TagImage "${TARGET_ARCH}-v${CERTBOT_VERSION}" "v${CERTBOT_VERSION}"
        TagImage "${TARGET_ARCH}-latest" "latest"
    fi
done
