#!/bin/bash
set -ex

DEFAULT_ARCH="amd64"
BUILD_ARCH=$(echo "$DOCKER_TAG" | cut -d '-' -f 1)

RemoveQemuStatic() {
    case "$1" in
        "amd64")
            QEMU_ARCH="x86_64"
            ;;
        "arm32v6")
            QEMU_ARCH="arm"
            ;;
        "*")
            echo "Not supported build architecture."
            exit -1
    esac
    rm -f qemu-${QEMU_ARCH}-static
}

if [ "${BUILD_ARCH}" == "${DEFAULT_ARCH}" ]; then
    echo "Default architecture. Nothing to do."
    exit 0
fi

RemoveQemuStatic "${BUILD_ARCH}"
