#!/bin/bash
set -ex

DEFAULT_ARCH="amd64"
BUILD_ARCH=$(echo "$DOCKER_TAG" | cut -d '-' -f 1)
CERTBOT_VERSION=$(echo "$DOCKER_TAG" | cut -d '-' -f 2 | sed "s/v//")

TagImage() {
    docker tag "${DOCKER_REPO}:$1" "${DOCKER_REPO}:$2"
    docker push "${DOCKER_REPO}:$2"
}

TagImage "${BUILD_ARCH}-v${CERTBOT_VERSION}" "${BUILD_ARCH}-latest"
if [ "${BUILD_ARCH}" == "${DEFAULT_ARCH}" ]; then
    TagImage "${BUILD_ARCH}-v${CERTBOT_VERSION}" "v${CERTBOT_VERSION}"
    TagImage "${BUILD_ARCH}-latest" "latest"
fi
