#!/bin/bash
set -ex

WORK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source "$WORK_DIR/../../lib/common"

QEMU_ARCH=$(GetQemuArchFromTag "$DOCKER_TAG")

RemoveQemuStatic "${QEMU_ARCH}"
