#!/bin/bash
set -ex

# Current supported architectures
export ALL_TARGET_ARCH=(amd64 arm32v6 arm64v8)

# Architecture used in tags with no architecture especified (certbot/certbot:latest, certbot/cerbot:v0.35.0, ...)
export DEFAULT_ARCH=amd64

# Enable manifests
export DOCKER_CLI_EXPERIMENTAL=enabled

# Returns certbot version (ex. v0.35.0 returns 0.35.0)
# Usage: GetCerbotVersionFromTag <DOCKER_VERSION>
GetCerbotVersionFromTag() {
    TAG=$1
    echo "${TAG//v/}"
}

# Returns the translation from Docker to QEMU architecture
# Usage: GetQemuArch [amd64|arm32v6|arm64v8]
GetQemuArch() {
    ARCH=$1

    case "$ARCH" in
        "amd64")
            echo "x86_64"
            ;;
        "arm32v6")
            echo "arm"
            ;;
        "arm64v8")
            echo "aarch64"
            ;;
        "*")
            echo "Not supported build architecture '$1'." >&2
            exit -1
    esac
}

GetManifestBoard() {
    ARCH=$1

    case "$ARCH" in
        "amd64")
            echo "--os linux --arch amd64"
            ;;
        "arm32v6")
            echo "--os linux --arch arm"
            ;;
        "arm64v8")
            echo "--os linux --arch arm64"
            ;;
        "*")
            echo "Not supported build architecture '$1'." >&2
            exit -1
    esac
}

# Downloads QEMU static binary file for architecture
# Usage: DownloadQemuStatic [x86_64|arm|aarch64]
DownloadQemuStatic() {
    ARCH=$1

    QEMU_ARCH=$(GetQemuArch "$ARCH")
    if [ ! -f "qemu-${QEMU_ARCH}-static" ]; then
        QEMU_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
        QEMU_LATEST_TAG=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/tags \
            | grep 'name.*v[0-9]' \
            | head -n 1 \
            | cut -d '"' -f 4)
        curl -SL "${QEMU_DOWNLOAD_URL}/${QEMU_LATEST_TAG}/x86_64_qemu-$QEMU_ARCH-static.tar.gz" \
            | tar xzv
    fi
}

# Executes the QEMU register script
# Usage: RegisterQemuHandlers
RegisterQemuHandlers() {
    docker run --rm --privileged multiarch/qemu-user-static:register --reset
}

# Builds docker certbot core image for a specific architecture and certbot version (ex. 0.35.0).
# Usage: BuildDockerCoreImage [amd64|arm32v6|arm64v8] <CERTBOT_VERSION>
BuildDockerCoreImage() {
    ARCH=$1
    VERSION=$2

    QEMU=$(GetQemuArch "$ARCH")
    docker build \
        --build-arg CERTBOT_VERSION="${VERSION}" \
        --build-arg TARGET_ARCH="${ARCH}" \
        --build-arg QEMU_ARCH="${QEMU}" \
        -f "${DOCKERFILE_PATH}" \
        -t "${DOCKER_REPO}:${ARCH}-v${VERSION}" \
        .
}

# Builds docker certbot plugin image for a specific architecture and certbot version (ex. 0.35.0).
# Usage: BuildDockerPluginImage [amd64|arm32v6|arm64v8] <CERTBOT_VERSION> <PLUGIN_NAME>
BuildDockerPluginImage() {
    ARCH=$1
    VERSION=$2
    PLUGIN=$3

    QEMU=$(GetQemuArch "$ARCH")
    docker build \
        --build-arg CERTBOT_VERSION="${VERSION}" \
        --build-arg TARGET_ARCH="${ARCH}" \
        --build-arg QEMU_ARCH="${QEMU}" \
        --build-arg PLUGIN_NAME="${PLUGIN}" \
        -f "${DOCKERFILE_PATH}" \
        -t "${DOCKER_REPO}:${ARCH}-v${VERSION}" \
        .
}

# Pushes docker image for a specific architecture and certbot version (ex. 0.35.0).
# Usage: BuildDockerCoreImage [amd64|arm32v6|arm64v8] <CERTBOT_VERSION>
PushDockerImage() {
    ARCH=$1
    VERSION=$2

    docker push "${DOCKER_REPO}:${ARCH}-v${VERSION}"
}

# Creates docker image "latest" tag for a specific architecture and certbot version, and pushes it.
# As an example, for version 0.35.0 in arm32v6:
#  - certbot/certbot:arm32v6-latest
# Usage: PushDockerImageAliases [amd64|arm32v6|arm64v8] <CERTBOT_VERSION>
PushDockerImageAliases() {
    ARCH=$1
    VERSION=$2

    docker tag "${DOCKER_REPO}:${ARCH}-v${VERSION}" "${DOCKER_REPO}:${ARCH}-latest"
    docker push "${DOCKER_REPO}:${ARCH}-latest"
}

# Prepare the multiarch docker manifests for the given architectures and certbot version, and pushes it.
# As an example, for version 0.35.0:
#  - certbot/certbot:v0.35.0
#  - certbot/certbot:latest
# Usage: TagDockerImageAliases <CERTBOT_VERSION>
PushMultiarchManifest() {
    VERSION=$1

    MANIFEST_TAG=""
    MANIFEST_LATEST=""
    for ARCH in ${ALL_TARGET_ARCH[@]}; do
        MANIFEST_TAG="$MANIFEST_TAG ${DOCKER_REPO}:${ARCH}-v${VERSION}"
        MANIFEST_LATEST="$MANIFEST_LATEST ${DOCKER_REPO}:${ARCH}-latest"
    done
    docker manifest create "${DOCKER_REPO}:v${VERSION}" $MANIFEST_TAG
    docker manifest create "${DOCKER_REPO}:latest" $MANIFEST_LATEST
    for ARCH in ${ALL_TARGET_ARCH[@]}; do
        docker manifest annotate "${DOCKER_REPO}:v${VERSION}" "${DOCKER_REPO}:${ARCH}-v${VERSION}" $(GetManifestBoard "${ARCH}")
        docker manifest annotate "${DOCKER_REPO}:latest" "${DOCKER_REPO}:${ARCH}-latest" $(GetManifestBoard "${ARCH}")
    done
}

