#!/bin/bash

GetCerbotVersionFromTag() {
    echo "$1" | cut -d '-' -f 2 | sed "s/v//"
}

GetTargetArchFromTag() {
    echo "$1" | cut -d '-' -f 1
}

GetQemuArchFromTag() {
    ARCH=$(echo "$1" | cut -d '-' -f 1)
    case "$ARCH" in
        "amd64")
            echo "x86_64"
            ;;
        "arm32v6")
            echo "arm"
            ;;
        "*")
            echo "Not supported build architecture '$ARCH'." >&2
            exit -1
    esac
}

DownloadQemuStatic() {
    QEMU_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
    QEMU_LATEST_TAG=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/tags \
        | grep 'name.*v[0-9]' \
        | head -n 1 \
        | cut -d '"' -f 4)
    curl -SL "${QEMU_DOWNLOAD_URL}/${QEMU_LATEST_TAG}/x86_64_qemu-$1-static.tar.gz" \
        | tar xzv
}

RegisterQemuHandlers() {
    if [ "$1" != "x86_64" ]; then
        docker run --rm --privileged multiarch/qemu-user-static:register --reset
    fi
}

RemoveQemuStatic() {
    rm -f "qemu-$1-static"
}
