#!/bin/bash

ALL_TARGET_ARCH=(amd64 arm32v6 arm64v8)

GetCerbotVersionFromTag() {
    echo "$1" | sed "s/v//"
}

GetQemuArch() {
    case "$1" in
        "amd64")
            echo "x86_64"
            ;;
        "arm32v6")
            echo "arm"
            ;;
        "arm64v8")
            echo "aarch64"
            ;;
        "*")
            echo "Not supported build architecture '$1'." >&2
            exit -1
    esac
}

DownloadQemuStatic() {
    QEMU_ARCH=$(GetQemuArch "$1")
    if [ ! -f "qemu-${QEMU_ARCH}-static" ]; then
        QEMU_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
        QEMU_LATEST_TAG=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/tags \
            | grep 'name.*v[0-9]' \
            | head -n 1 \
            | cut -d '"' -f 4)
        curl -SL "${QEMU_DOWNLOAD_URL}/${QEMU_LATEST_TAG}/x86_64_qemu-$QEMU_ARCH-static.tar.gz" \
            | tar xzv
    fi
}

RegisterQemuHandlers() {
    docker run --rm --privileged multiarch/qemu-user-static:register --reset
}
